name: sub

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
          
      - name: Install Package
        id: set
        continue-on-error: true
        run: |
          sudo languagesetup -langspec ja
          sudo systemsetup -settimezone Asia/Tokyo
          sudo systemsetup -getusingnetworktime
          sudo systemsetup -setusingnetworktime on
          pip install chromedriver-binary-auto
          pip install selenium-wire
          pip install selenium
          pip install requests
      
      
      - name: Error handling
        if: ${{ steps.set.outcome == 'failure' }}
        run: |
          echo "Error handling"
          curl -X POST https://api.github.com/repos/nao-riku/334Ranker/dispatches \
               -H 'authorization: Bearer '${{ secrets.KEY }} \
               --data '{"event_type": "Error handling"}'
          exit 1
 

      - name: Run Python
        id: python
        continue-on-error: true
        timeout-minutes: 350
        env:
          GAS_URL: ${{ secrets.GAS_URL }}
          HTML_URL: ${{ secrets.HTML_URL }}
          HTML_URL2: ${{ secrets.HTML_URL2 }}
          PASS: ${{ secrets.PASS }}
          TEL: ${{ secrets.TEL }}
          TZ: "Asia/Tokyo"
        run: python main.py test

      
      - name: Error handling
        if: ${{ steps.python.outcome == 'failure' }}
        run: |
          echo "Error handling"
          curl -X POST https://api.github.com/repos/nao-riku/334Ranker/dispatches \
               -H 'authorization: Bearer '${{ secrets.KEY }} \
               --data '{"event_type": "Error handling"}'
          exit 1
